### ISSUE TITLE
build on win32

### ISSUE THREAD

**Issue by sherpya** [jlaine/qdjango#37]
`util.cpp` needs `QDjangoDatabase::databaseType` but it's not exported so I added `QDJANGO_EXPORT` to `QDjangoDatabase` class but then the unresolved symbol changes:

```
QDjangoScript.obj:-1: error: LNK2001: unresolved external symbol "public: static struct QMetaObject const QDjangoDatabase::staticMetaObject" (?staticMetaObject@QDjangoDatabase@@2UQMetaObject@@B)
```

while qdjangoscript build instead normally, the linux build is fine, but the export keyword is mandatory on win32

**Comment by mikeboutch** [comment]
I have exactly the same problem..

And I have a  QDJANGO_EXPORT to QDjangoDatabase...

see the build result:

but still the same problem....
1>------ Rebuild All started: Project: qdjango-db, Configuration: Debug x64 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(298,5): warning MSB8004: Intermediate Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Intermediate Directory.
1>  Moc'ing QDjangoModel.h...
1>  Moc'ing QDjango_p.h...
1>  moc_QDjangoModel.cpp
1>  moc_QDjango_p.cpp
1>  QDjango.cpp
1>  QDjangoMetaModel.cpp
1>  QDjangoModel.cpp
1>  QDjangoQuerySet.cpp
1>  QDjangoWhere.cpp
1>  Generating Code...
1>     Creating library .\\qdjango-db0.lib and object .\\qdjango-db0.exp
1>  qdjango-db.vcxproj -> C:\tools\qdjango\src\db\.\qdjango-db0.dll
2>------ Rebuild All started: Project: qdjango-script, Configuration: Debug x64 ------
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(298,5): warning MSB8004: Intermediate Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Intermediate Directory.
2>  QDjangoScript.cpp
2>     Creating library .\\qdjango-script0.lib and object .\\qdjango-script0.exp
2>QDjangoScript.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QDjangoDatabase::staticMetaObject" (?staticMetaObject@QDjangoDatabase@@2UQMetaObject@@B)
2>.\\qdjango-script0.dll : fatal error LNK1120: 1 unresolved externals
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by liwey** [comment]
yes, I have exactly the same problem.
I patch it like this:
in file script.pro add:
!contains(QDJANGO_LIBRARY_TYPE,staticlib) { # patch for script
    DEFINES += BUILD_QDJANGO_SCRIPT
}

in file QDjango_p.h:
#if defined(QDJANGO_SHARED)
#  if defined(QDJANGO_BUILD)
#    if defined(BUILD_QDJANGO_SCRIPT)  // patch for script
#      define QDJANGO_EXPORT Q_DECL_IMPORT
#    else
#      define QDJANGO_EXPORT Q_DECL_EXPORT
#    endif
#  else
#    define QDJANGO_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define QDJANGO_EXPORT
#endif
