### ISSUE TITLE
Unnecessary template usage

### ISSUE THREAD

**Issue by ericLemanissier** [jlaine/qdjango#39]
I recently started to use QDjango, it's great and works very well !
However, there is one thing which seems not ideal in our context of use : It is nearly impossible to use without template, because of QDjangoQuerySet.
What we aim at is to encapsulate all QDjango access in a single class, which can save, load, delete, all kind of objects in our application. It would be a lot easier if we could just pass/return qobject pointers to these functions without template (for example to connect signals and slots).
I started to modify the QDjangoQuerySet to be template-less, and I have a first version which seems to work. I did not go change the unit tests yet, but I can.
Do you consider it would be worth ? Is there any chance this feature would be merged if i made a pull request ?

**Comment by jlaine** [comment]
QDjangoQuerySet is a template in order to convey the type information along with the queryset. Unless I am mistaken, the alternative is to ask QDjango users to sprinkle qobject_cast's all over their code.
