### ISSUE TITLE
Create a quickstart guide

### ISSUE THREAD

**Issue by RazZziel** [jlaine/qdjango#40]
At first glance it's difficult to see how QDjango can help my project; I think users would greatly appreciate some sort of quickstart guide with a simple example on how the library is supposed to be used.

I think a good example is the readme of https://github.com/sandeepmistry/bleno

**Comment by jlaine** [comment]
Is this what you are looking for?

http://doc.qdjango.org/qdjango-snapshot/models.html

**Comment by RazZziel** [comment]
Looks good! I actually had browsed the Http documentation, but at first sight it looked like just an API reference. Maybe an Http module usage guide could be added, and these guides could be linked from Github's README for quicker discovery to new users?

**Comment by jlaine** [comment]
I don't plan to address this myself. Please re-open if you actually plan to submit the documentation.
