### ISSUE TITLE
Please migrate QtScript usage to QJSEngine (support will be removed in Qt 5.6)

### ISSUE THREAD

**Issue by pete-woods** [jlaine/qdjango#44]
QtScript is currently deprecated, and in Qt 5.6 it will be removed.

I currently use QDjango for one of the components in Ubuntu Touch (the infographics on the lock screen). See (https://bugs.launchpad.net/ubuntu/+source/libusermetrics/+bug/1457488).

Apparently the replacement for QtScript is QJSEngine (http://doc.qt.io/qt-5/qtjavascript.html).

Thanks!

**Comment by jlaine** [comment]
Hi Pete,

Thanks for bringing this up. I am wondering whether a new qdjango-js library as a replacement for qdjango-script might be the right way to go?

**Comment by pete-woods** [comment]
Sounds reasonable to me. If you make the qdjango-script library an optional build component, then we can just disable it when QtScript stops being available.

**Comment by jlaine** [comment]
Do you have any feedback on the current QtScript-based API so we can make the QJSEngine-based one better? Can you point me to the code where you make use of the QtScript bindings?

**Comment by pete-woods** [comment]
Unfortunately not. I don't actually use it.

In reality I could get away just with the library build being optional, and then not building it in Ubuntu when 5.6 is released.

**Comment by pete-woods** [comment]
Updated my first comment where I mistakenly said I used qdjangoscript, rather than just qdjango.

**Comment by jlaine** [comment]
Ah OK, in that case I would be in favor of simply disabling QtScript support  when building against Qt5

**Comment by pete-woods** [comment]
Or at least Qt >= 5.6

**Comment by pete-woods** [comment]
If I knew QMake, I'd already have a pull request for you, but sadly I'm only familiar with CMake.

**Comment by pete-woods** [comment]
Something like that?

**Comment by jlaine** [comment]
Pete, I have given it some thought and I am going to simply pull qdjango-script:

- This code is not on par with the rest of QDjango quality-wise
- I have never received any questions, issues or any sort of feedback about it
- I do not believe there is a valid case for using it.
- QtScript being dropped is a strong signal that this technology is obsolete.

**Comment by pete-woods** [comment]
Okay, sounds good to me. Just need a release of 0.6.0 now :)

**Comment by pete-woods** [comment]
Oh cool, you already did it! Now to upload it to the Ubuntu archive.

**Comment by jlaine** [comment]
Can we coordinate on that please? I am in the process of moving Debian's packaging to git in collab-maint and would like for us to take the chance to resync Ubuntu/Debian packaging.

**Comment by pete-woods** [comment]
I think I will just wait for you to upload to Debian when you feel it's appropriate. Then we can merge the changes into Ubuntu when that happens. FYI, the only packaging difference between the two is that we build with Qt 5 by default on Ubuntu.
