### ISSUE TITLE
Handling QString() for NOT NULL fields

### ISSUE THREAD

**Issue by jerch** [jlaine/qdjango#47]
Is there any specific reason for returning `QLatin1String("")` here?
https://github.com/jlaine/qdjango/blob/master/src/db/QDjangoMetaModel.cpp#L203

It converts null strings to empty strings and bypasses NOT NULL rules. For my case returning `QVariant()` instead fixed the behavior.

**Comment by jlaine** [comment]
Yes, there is a specific reason : this is a field which has been marked as NOT NULL, so we return an empty string. If you want a nullable field add:

Q_CLASSINFO("field_name", "null=true")

to your model

**Comment by jerch** [comment]
Ah sorry my description was misleading. What I was looking for was a NOT NULL field, where the database rejects `save` if that field was not set, as Django does.
